cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos/no-speakers-metallb-native.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos/ipaddress_pools.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos/l2advertisement.yaml
  controlPlane:
    endpoint: https://192.168.130.90:6443 
  network:
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
    cni:
      name: custom
      urls:
        - https://github.com/desrig869/Talos-dev/raw/main/Talos/tigera-operator.yaml
        - https://github.com/desrig869/Talos-dev/raw/main/Talos/tigera-custom-resources.yaml
        - https://github.com/desrig869/Talos-dev/raw/main/Talos/calico-bgp.yaml
machine:
  kubelet:
    extraArgs:
      rotate-server-certificates: true
# Setup docker pull proxies
  registries:
    mirrors:
      docker.io:
        endpoints:
          - http://192.168.1.40:5000
      gcr.io:
        endpoints:
          - http://192.168.1.40:5003
      ghcr.io:
        endpoints:
          - http://192.168.1.40:5004
      registry.k8s.io:
        endpoints:
          - http://192.168.1.40:5001
