os: "linux"
arch: "amd64"


cluster_name: Talos-dev

# talos_version: factory.talos.dev/installer/f23bd49f9b270302e76953d26f8b2332aa053c854def54eb85593374955a415d:v1.9.4
# talos_version: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.9.4

#             - siderolabs/iscsi-tools
#            - siderolabs/qemu-guest-agent
# talos_version: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586:v1.9.4
# talosctl_version: v1.9.4

#             - siderolabs/iscsi-tools
#            - siderolabs/qemu-guest-agent
talos_version: factory.talos.dev/nocloud-installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586:v1.10.5
talosctl_version: v1.10.5




control_plane_ip: 192.168.130.91

Control_planes:
  control_plane_1: '{{control_plane_ip}}'
  control_plane_2: '192.168.130.92'
  control_plane_3: '192.168.130.93'
Workers:
  worker_1: '192.168.130.94'
  worker_2: '192.168.130.95'
  worker_3: '192.168.130.96'

config_directory: "/home/{{ ansible_user }}/.talos"
config_file: "/home/{{ ansible_user }}/.talos/talosconfig"
talconf_dir: "/home/{{ ansible_user }}/talconf"

kube_vip_version: "v0.8.0"
vip_interface: eth0
vip: 192.168.130.90

metallb_version: v0.13.12
lb_range: 192.168.90.0/24
lb_pool_name: first-pool

ansible_user: devman
ansible_become: true
ansible_become_method: sudo
