cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos-dev/tigera-custom-resources.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos-dev/custom-resources.yaml 
    - https://github.com/desrig869/Talos-dev/raw/main/Talos-dev/no-speakers-metallb-native.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos-dev/ipaddress_pools.yaml
    - https://github.com/desrig869/Talos-dev/raw/main/Talos-dev/l2advertisement.yaml
  controlPlane:
    endpoint: https://192.168.130.90:6443 
  network:
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
    cni:
      name: none
machine:
  network:
    interfaces:
    - interface: eth0
      vip:
        ip: 192.168.130.90
  kubelet:
    extraArgs:
      rotate-server-certificates: true
