cluster:
#  controlPlane:
#    endpoint: https://192.168.130.90:6443 
  network:
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
    cni:
      name: none
machine:
  network:
    interfaces:
    - interface: eth0
      vip:
        ip: 192.168.130.90
# Setup docker pull proxies
  registries:
    mirrors:
      docker.io:
        endpoints:
          - http://192.168.1.40:5000
      gcr.io:
        endpoints:
          - http://192.168.1.40:5003
      ghcr.io:
        endpoints:
          - http://192.168.1.40:5004
      registry.k8s.io:
        endpoints:
          - http://192.168.1.40:5001
